---
- name: Create deployment directory
  file:
    path: "{{ deploy_path }}"
    state: directory
    mode: '0755'

- name: Copy .NET application files (if building locally)
  copy:
    src: files/app/
    dest: "{{ deploy_path }}/app/"
  when: build_locally | default(false)

- name: Build .NET Docker image locally (optional)
  command: docker build -t "{{ app_image }}" "{{ deploy_path }}/app/"
  args:
    chdir: "{{ deploy_path }}"
  when: build_locally | default(false)

- name: Deploy .env file
  template:
    src: .env.j2
    dest: "{{ deploy_path }}/.env"
    mode: '0600'

- name: Deploy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ deploy_path }}/docker-compose.yml"

- name: Start Docker Compose stack
  command: docker compose up -d
  args:
    chdir: "{{ deploy_path }}"
  register: compose_result
  changed_when: "'Starting' in compose_result.stdout or 'Recreating' in compose_result.stdout"